### ISSUE TITLE
모니터링

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/android-library#12]
애플리케이션 개발 및 사용 모니터링 설정.

## TODO

- [ ] Firebase 프로젝트 설정.
- [ ] Crashlytics에 에러 리포트.
- [ ] CI 리포트를 Firebase Hosting으로 배포.
- [ ] CD 리포트를 Firebase Hosting으로 배포.
