### ISSUE TITLE
부가기능을 추가한 뷰모델 작성.

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/android-library#3]
여러 사용자 시나리오에 대응할 수 있는 뷰모델 작성.

## TODO

- ~~Hilt 의존성 및 설정 추가.~~ : 다른 이슈로 분리.
- [x] 샘플 앱에 화면 이동 추가.
- [x] UI 라이프사이클 인식.
- [x] 프로그레스 인디케이터 관리.
