### ISSUE TITLE
UI 요소 추가.

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/android-library#6]
Compose 네비게이션 개선과 UI 상태 관리 갠선을 보이기 위해 미리 UI 요소를 추가한다.

## TODO

- [x] `Scaffold` 레이아웃 추가.
- [x] 하단 탭 바 추가 : 게임, 기록.
- [x] 상단 타이틀바 추가.
