### ISSUE TITLE
예외처리 공통화.

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/android-library#7]
앱 실행중 발생하는 예외를 공통으로 처리할 수 있도록 컴포넌트를 추가한다.

## TODO

- [x] 기본 예외 핸들러.
- [x] 코루틴 기본 예외 핸들러.
- [x] `viewModelScope`용 예외 핸들러.
