### ISSUE TITLE
UI 내비게이션 오브젝트화.

### ISSUE THREAD

**Issue by hemoptysisheart** [hemoptysisheart/android-library#9]
화면이동을 개발하는 각 개발자가 각각을 개발하는 것이 아니라, 한 곳에서 코드로 관리할 수 있도록 코드화 한다.

## TODO

- [x] `destination`(백스택 엔트리 대상) 설정.
- [x] 설정 코드를 사용한 네비게이션 그래프 생성.
- [x] 설정 코드를 사용한 화면 이동 및 인터랙션 제어.
